<?php

namespace Database\Seeders;

use App\Models\order;
use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $orders = [
            [
                'customer_id' => 1,
                'product_id' => 3,
                'quantity' => 2,
                'review' => 'Good product, satisfied with the purchase.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 7,
                'quantity' => 1,
                'review' => 'Average product, expected better quality.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3,
                'product_id' => 8,
                'quantity' => 3,
                'review' => 'Excellent product, exceeded my expectations!',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4,
                'product_id' => 5,
                'quantity' => 2,
                'review' => 'Very satisfied with the purchase, highly recommend.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5,
                'product_id' => 6,
                'quantity' => 1,
                'review' => 'Not as expected, had some issues with the product.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 1,
                'product_id' => 3,
                'quantity' => 2,
                'review' => 'Good product, would buy again.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 2,
                'product_id' => 7,
                'quantity' => 1,
                'review' => 'Poor quality, disappointed with the purchase.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 3,
                'product_id' => 8,
                'quantity' => 3,
                'review' => 'Satisfactory product, met my requirements.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 4,
                'product_id' => 5,
                'quantity' => 2,
                'review' => 'Mixed feelings about the product, could be better.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 5,
                'product_id' => 6,
                'quantity' => 1,
                'review' => 'Decent product, but had some issues with delivery.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 6,
                'product_id' => 9,
                'quantity' => 2,
                'review' => 'Product arrived on time, happy with the purchase.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 7,
                'product_id' => 10,
                'quantity' => 1,
                'review' => 'Not as described, had to return it for a refund.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 8,
                'product_id' => 3,
                'quantity' => 3,
                'review' => 'Very happy with the product, excellent value for money.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 9,
                'product_id' => 8,
                'quantity' => 2,
                'review' => 'Average product, did not meet all expectations.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 10,
                'product_id' => 5,
                'quantity' => 1,
                'review' => 'Highly recommended, excellent customer service.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 11,
                'product_id' => 1,
                'quantity' => 2,
                'review' => 'Good product, but a bit pricey for the quality.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 12,
                'product_id' => 3,
                'quantity' => 1,
                'review' => 'Happy with the purchase, would buy from this seller again.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 13,
                'product_id' => 5,
                'quantity' => 3,
                'review' => 'Product arrived damaged, had to request a replacement.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 14,
                'product_id' => 6,
                'quantity' => 2,
                'review' => 'Very satisfied with the product, thank you!',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 15,
                'product_id' => 7,
                'quantity' => 1,
                'review' => 'Disappointed with the product quality, expected better.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 16,
                'product_id' => 8,
                'quantity' => 2,
                'review' => 'Product meets expectations, would recommend.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 17,
                'product_id' => 9,
                'quantity' => 3,
                'review' => 'Great product, fast delivery!',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 18,
                'product_id' => 10,
                'quantity' => 1,
                'review' => 'Received wrong item, had to contact support for resolution.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 19,
                'product_id' => 8,
                'quantity' => 2,
                'review' => 'Product as described, happy with the purchase.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 20,
                'product_id' => 3,
                'quantity' => 1,
                'review' => 'Product arrived late, but otherwise satisfied.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'customer_id' => 11,
                'product_id' => 1,
                'quantity' => 3,
                'review' => 'Great product, very satisfied with the purchase.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 12,
                'product_id' => 5,
                'quantity' => 1,
                'review' => 'Product arrived damaged, had to request a replacement.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 13,
                'product_id' => 3,
                'quantity' => 2,
                'review' => 'Not as expected, had issues with the size.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 14,
                'product_id' => 6,
                'quantity' => 1,
                'review' => 'Satisfied with the product quality, but delivery was slow.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 15,
                'product_id' => 7,
                'quantity' => 2,
                'review' => 'Excellent service and fast delivery!',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 16,
                'product_id' => 9,
                'quantity' => 3,
                'review' => 'Product quality was good, would buy again.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 17,
                'product_id' => 10,
                'quantity' => 1,
                'review' => 'Disappointed with the product, had issues with durability.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 18,
                'product_id' => 1,
                'quantity' => 2,
                'review' => 'Product met my expectations, good value for money.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 19,
                'product_id' => 3,
                'quantity' => 1,
                'review' => 'Product was delivered on time, but had some minor issues.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'customer_id' => 20,
                'product_id' => 5,
                'quantity' => 2,
                'review' => 'Very satisfied with the product, would recommend to others.',
                'is_received' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert the orders into the database
        foreach ($orders as $order) {
            order::create($order);
        }
    }
}
